_target_: src.models.autoencoder.AutoEncoder

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

encoder:
  _target_: src.models.components.pointnetpp.Net

decoder:
  _target_: src.models.components.decoder.Decoder
  channels: 1024
  num_points: 1024

# compile model for faster training with pytorch 2.0
compile: false
