# @package _global_

defaults:
  - _self_
  - data: oakink
  - model: autoencoder
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: /root/autodl-tmp/project/pointcloud-representation-learning/logs/train/runs/2023-10-05_14-36-06/checkpoints/last.ckpt
ckpt_path: /root/autodl-tmp/project/pointcloud-representation-learning/logs/train/runs/2023-10-07_13-52-41/checkpoints/last.ckpt
